---
version: 2
executorType: docker
containerInfo:
  - image: jimmycuadra/rust:latest
stages:
  build:
    steps:
      - type: shell
        shell: /bin/bash
        command: cargo build
      - type: shell
        shell: /bin/bash
        command: cargo test
